const timeZones = [
  'Pacific/Auckland',
  'Pacific/Fiji',
  'Australia/Sydney',
  'Australia/Brisbane',
  'Asia/Tokyo',
  'Asia/Manila',
  'Asia/Bangkok',
  'Indian/Chagos',
  'Asia/Karachi',
  'Asia/Dubai',
  'Europe/Moscow',
  'Europe/Helsinki',
  'Europe/Paris',
  'Europe/London',
  'Atlantic/Azores',
  'America/Noronha',
  'America/Sao_Paulo',
  'America/Barbados',
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Anchorage',
  'Pacific/Honolulu',
]

export default timeZones